[tool.poetry]
name = "helikite-data-processing"
version = "0.1.0"
description = "Library to generate quicklooks and data quality checks on Helikite campaigns"
authors = ["Evan Thomas <evan.thomas@epfl.ch>"]
readme = "README.md"
packages = [{include = "helikite_data_processing"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.3"
pydantic = "^1.10.5"
plotly = "^5.13.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
