# List all of the instruments that the processing tool should include
#
# The config of each instrument should be defined in /helikite/config, and the
# value assigned to 'config:' represents the import within __init__.py within
# the config folder.
#
# The initial value of the file is set to null unless this is defined previously
instruments:
    flight_computer:
        config: FlightComputer
        file: null
    mcpc:
        config: MCPC
        file: null
    msems-readings:
        config: MSEMSReadings
        file: null
    msems-inverted:
        config: MSEMSInverted
        file: null
    ozone:
        config: OzoneMonitor
        file: null
    pico:
        config: Pico
        file: null
    pops:
        config: POPS
        file: null
    smart_tether:
        config: SmartTether
        file: null
    stap:
        config: STAP
        file: null
settings:
    input_folder: input
    output_folder: output
