name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]  # or 'master' or whatever your main branch is

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match your dev version

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-autoapi sphinx-rtd-theme

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
